<a href="https://colab.research.google.com/github/uzairazmat/Numpy-Exercise/blob/main/1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1.Import Numpy


In [1]:
import numpy as np

## 2.Set seed (1337)

In [2]:
np.random.seed(1337)

## 3.1 Bassics of matrixes

## 3.1.1 create 1-rank tensor

In [3]:
a1 = np.array([1,2,3,5])

In [4]:
a1.shape

(4,)

## 3.1.2 create (2,4) shape

In [5]:
a2 = np.array([[1,2,3,4]
               ,[5,6,7,8]])

In [6]:
a2.shape

(2, 4)

## 3.1.3 create (1,3) shape

In [7]:
a3 = np.array([
    [1,2,3]
    ]
              )  #this is essentially called row-vector

In [8]:
a3.shape

(1, 3)

## 3.1.4 create (999,) shape

In [9]:
a4 = np.arange(1,1000,1)
a4[:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
a4.shape

(999,)

## 3.1.5 create (10,) shape to (5,2)

In [11]:
a5 = np.arange(0.5 , 10 , 1)

In [12]:
a5.shape

#  this operation is very useful in machine learning and image processing
#     some algorithm provides you some specific shape and some need specific
#     shape like neural network (1-rank-tensor) so you need to reshape

(10,)

## linespace()

In [13]:
# evenly spaced but we don't know steps

a6 = np.linspace(3,5,10)
print(a6)

[3.         3.22222222 3.44444444 3.66666667 3.88888889 4.11111111
 4.33333333 4.55555556 4.77777778 5.        ]


## print this 3.22222222

In [14]:
a6[1]

3.2222222222222223

# 3.2 Bassic Operation

## Matrix of zeores having shae (3,5)

In [15]:
a1  = np.zeros((3,5))
a1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Matrix of ones having shae (3,5)

In [16]:
a2 = np.ones((3,5))
a2

# by defaults numpy operation works in floats

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## changing specific values

In [17]:
a3 = np.arange(1,7,1)
a3

array([1, 2, 3, 4, 5, 6])

In [18]:
a3[2] = 4
a3

array([1, 2, 4, 4, 5, 6])

In [19]:
a3[:3] = 10
a3  #assigning multiple locations

array([10, 10, 10,  4,  5,  6])

In [20]:
a3[:3] = [1,2,3]
a3

array([1, 2, 3, 4, 5, 6])

## Most useful case

In [21]:
a4 = np.zeros((2,2))
a4[0,0] = 1
a4[0,1] = 2
a4[1,0] = 3

a4


array([[1., 2.],
       [3., 0.]])

# Array operation

In [22]:
a4

array([[1., 2.],
       [3., 0.]])

## plus 2 with all elements of a4
``` Note! if you are comming from math background you know scalar not add with vector but it's obvious as an programming backgroud ```

In [23]:
a4+2  #means add 2 with every element of b
a4  # note it's not inplace operation
    #it makes copy
    # so that's why it not applicable for a large scale

array([[1., 2.],
       [3., 0.]])

## sqaure  of a matrix
``` Note in math square of a matrix means you multiply matrix with it's own but here it square's element wise ```


# sum(), b.sum() , b.sum(axis = 0) ,b.sum(axis = 1)
```  it's always return a 1-rank tensors ```

In [24]:
sum(a4)  #it's sum's coloumn wise

array([4., 2.])

In [25]:
print(a4)
a4.sum()

[[1. 2.]
 [3. 0.]]


6.0

In [26]:
a4.sum(axis=0) # it's same's as sum()

array([4., 2.])

In [27]:
a4.sum(axis = 1) #it sum's row wise

array([3., 3.])

In [28]:
a = np.array([[1,2],[5,6]])
b = np.array([[9,1],[1,1]])
print(a)
print(b)

[[1 2]
 [5 6]]
[[9 1]
 [1 1]]


In [29]:
a+b #row wise addition


array([[10,  3],
       [ 6,  7]])

In [30]:
a*b

array([[9, 2],
       [5, 6]])

In [31]:
a.dot(b)  #this is the actul maths operation

array([[11,  3],
       [51, 11]])

In [32]:
a**b   #raise something to  the power of a matrix
        #it's valid maths

array([[1, 2],
       [5, 6]])

## tarnspose of a matrix

In [33]:
a = np.array([[1,2],[4,5],[7,8]])
print(a)
a.shape


[[1 2]
 [4 5]
 [7 8]]


(3, 2)

In [34]:
a.T
a.T.shape

(2, 3)

In [35]:
c = np.arange(1,4,1)  #creaeting 1-rank-tensor
c.shape

(3,)

In [36]:
c.T.shape  # Transpose of 1-rank-tensor is alway 1-rank tensor

(3,)

In [37]:
c.reshape(3,1).T.shape

(1, 3)

## Numpy broadcasting or "mapping" work for both scalars and arrayes

In [40]:
s = np.sqrt(4)
s

2.0

In [46]:
n = np.array([[1,2,3],[4,5,6]])
s = np.sqrt(n)  # calculate sqrt of every element in an np array
s

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

## Comparing with np array

In [48]:
n>3  #it's compare a sclar element wise

array([[False, False, False],
       [ True,  True,  True]])

In [49]:
n2 = np.array([[1,2,5],[4,5,8]])

In [50]:
n == n2

array([[ True,  True, False],
       [ True,  True, False]])

## Misc operations

In [63]:
# f(x) = 1/(1+e^(-x)
from math import e
""" sigmoid function A sigmoid function is an activation function that is used in neural networks to compress input values into a range between 0 and 1."""
def sigmoid(x):
  return 1. / (1 + e**(-x))
  #it's 0.5 on exactly 0 and 1 on +infinity


In [64]:
sigmoid(0)

0.5

In [67]:
sigmoid(-20)

2.061153618190206e-09

In [71]:
#see if we pass list to our sigmoid function
l = [1,2,3,4]
sigmoid(l)
#it's not our b/c our code is only work with scalars

TypeError: bad operand type for unary -: 'list'

In [74]:
# so you ee it's work correctly with np array
l = np.array(l)
sigmoid(l)

array([0.73105858, 0.88079708, 0.95257413, 0.98201379])